### ISSUE TITLE
Bug: Unable to use npm version

### ISSUE THREAD

**Issue by donroyco** [KrekkieD/buenos-commit-msg#2]
When trying to do release management via the command line using [npm's version](https://docs.npmjs.com/cli/version) I am unable to proceed, because it's not following the requested format.

```
random-repository git:(master) npm version patch
v0.0.2
npm ERR! Darwin 16.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "version" "patch"
npm ERR! node v6.9.2
npm ERR! npm  v3.10.9
npm ERR! code 1

npm ERR! Command failed: git commit -m 0.0.2
npm ERR! Commit message format failure, should follow this format:
npm ERR!     <type>(<scope>): <subject> <issue>
npm ERR! At least a type and subject is required
```

I think an exception should be written when trying to bump versions via the command line *or* the githook should take over the git commit message (`git commit -m 0.0.2`) and put it in the requested format, e.g. `git commit -m 'version(patch): 0.0.2'`.

**Comment by KrekkieD** [comment]
What about `npm version patch -m "version: 0.0.2"`?

**Comment by donroyco** [comment]
That seems to work. 

So, for every release version, use this:
```
npm version patch -m "version: 0.0.1"
npm version minor -m "version: 0.1.0"
npm version major -m "version: 1.0.0"
```
